/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f7f7f7',
        'surface-container': '#eeeeee',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e1e3e3',
        'surface-container-highest': '#e5e7eb',
        'surface-variant': '#f1f3f3',
        'surface-bright': '#ffffff',
        'surface-dim': '#d3d5d5',
        surface: '#F9FAFB',
        'on-surface': '#1A1C1C',
        'on-surface-variant': '#4B5563',
        'on-background': '#111827',
        background: '#F9FAFB',
        primary: '#EAB308',
        'primary-dim': '#5c4f00',
        'primary-container': '#FEF9C3',
        'primary-fixed': '#fddc00',
        'primary-fixed-dim': '#edce00',
        'on-primary': '#2D2600',
        'on-primary-container': '#5b4e00',
        'on-primary-fixed': '#463b00',
        'on-primary-fixed-variant': '#665800',
        'inverse-surface': '#111827',
        'inverse-primary': '#fddc00',
        'inverse-on-surface': '#9c9d9d',
        secondary: '#605e00',
        'secondary-container': '#FEF9C3',
        'secondary-fixed': '#ece856',
        'secondary-fixed-dim': '#ddda49',
        'on-secondary': '#1A1C1C',
        'on-secondary-container': '#565400',
        'on-secondary-fixed': '#434100',
        tertiary: '#4e6300',
        'tertiary-container': '#d7f874',
        'tertiary-fixed': '#d7f874',
        'tertiary-fixed-dim': '#c9ea68',
        'on-tertiary': '#e1ff87',
        'on-tertiary-container': '#4a5e00',
        'on-tertiary-fixed': '#3a4a00',
        error: '#EF4444',
        'error-dim': '#b92902',
        'error-container': '#FEE2E2',
        'on-error': '#ffefec',
        'on-error-container': '#991B1B',
        outline: '#8e9191',
        'outline-variant': '#d1d5db',
        'surface-tint': '#EAB308',
      },
      fontFamily: {
        body: ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
      },
    },
  },
  plugins: [],
};
